Ranga\CatalogBundle\Entity\Product:
    type: entity
    table: products
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        description:
            type: text
        summary:
            type: text
        isActive:
            type: boolean
        slug:
            type: string
            length: '255'
    manyToOne:
        brand:
            targetEntity: Brand
            joinColumn:
              name: brand_id
              referencedColumnName: id
    manyToMany:
        category:
          targetEntity: Category
          inversedBy: products
          joinTable:
              name: product_category
              joinColumns:
                product_id:
                  referencedColumnName: id
              inverseJoinColumns:
                catagory_id:
                  referencedColumnName: id
    
    lifecycleCallbacks: {  }
