parameters:
#    ranga_catalog.example.class: Ranga\CatalogBundle\Example

services:
#    ranga_catalog.example:
#        class: %ranga_catalog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
